services:
    nginx:
        image: nginx:latest
        container_name: nginx_loan
        ports:
            -   "3000:80"
        volumes:
            -   ./:/var/www/html
            -   ./docker/nginx/default.conf/:/etc/nginx/conf.d/default.conf
        depends_on:
            -   php
            -   mysql
        networks:
            - loan

    mysql:
        image: mysql:latest
        container_name: mysql_loan
        restart: unless-stopped
        tty: true
        volumes:
            -   ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: loan_ms
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - "3306:3306"
        networks:
            - loan

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php_loan
        volumes:
            - ./:/var/www/html
        ports:
            - "9001:9001"
        networks:
            - loan

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_loan
        platform: linux/amd64
        ports:
            - "8082:80"
        environment:
            PMA_HOST: mysql_loan
            PMA_PORT: 3306
            PMA_USER: root
            PMA_PASSWORD: password
        depends_on:
            - mysql
        networks:
            - loan

networks:
    loan:
        driver: bridge
